### PR TITLE
feat(click): use click

### PR DESCRIPTION
**Pull request by fantix**
* also updated `Pipfile` and .gitignore

### Improvements
* Using click for CLI now

### CODE REVIEW

**Review by paulineribeyre — COMMENTED** [review]
cool!! if possible, can you make `file_names` required?

**Comment by PlanXCyborg** [comment]
The style in this PR agrees with [`black`](https://github.com/ambv/black). :heavy_check_mark:

This formatting comment was generated automatically by a script in [uc-cdis/wool](https://github.com/uc-cdis/wool).

**Comment by paulineribeyre** [comment]
also `gen3users validate --help` does not show `file_names`

**Comment by fantix** [comment]
> also `gen3users validate --help` does not show `file_names`

Yes! I was confused too until found this:

https://click.palletsprojects.com/en/7.x/documentation/#help-texts

> Arguments cannot be documented this way. This is to follow the general convention of Unix tools of using arguments for only the most necessary things and to document them in the introduction text by referring to them by name.

**Review by paulineribeyre — APPROVED** [review]

**Comment by fantix** [comment]
Thx for approving! For using `six` in `setup.py`, it might be a problem for PyPI or other users running `python setup.py install` without Pipenv, so I kinda "fixed" it.

**Comment by paulineribeyre** [comment]
yeah, got it 😄

**Pull request merged**
